spring.profiles.active=local
spring.application.name=GATEWAY-AURORA
server.port=8080

spring.security.user.name=any-user
spring.security.user.password=any-password

jwt.secret=${JWT_SECRET}

#===========================
# EUREKA CONFIGS
#===========================
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

#=============================
# DOWNSTREAM SERVICE ROUTES
#=============================
route.frontend=${FRONTEND_URL:http://localhost:5173}

route.user=${USER_SERVICE:http://localhost:9000/user}
route.metadata=${METADATA_SERVICE:http://localhost:9003/metadata}