spring.application.name=USER-SERVICE
server.port=9000
server.servlet.context-path=/user

#===========================
# EUREKA CONFIGS
#===========================
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

#===========================
# DATABASE CONFIGURATIONS
#===========================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/streaming_db?currentSchema=user_schema
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#===========================
# REDIS CONFIGURATIONS
#===========================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.password=${REDIS_PASSWD}
spring.data.redis.port=6379

#===========================
# JWT CONFIGURATIONS
#===========================
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh=604800000