export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

export const ROLES = {
    VIEWER: 'ROLE_VIEWER',
    CREATOR: 'ROLE_CREATOR',
    ADMIN: 'ROLE_ADMIN',
    ADMINISTRATOR: 'ROLE_ADMINISTRATOR'
};
